/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * Flags for high level gimbal manager operation The first 16 bits are identical to the GIMBAL_DEVICE_FLAGS.
 */
public class GIMBAL_MANAGER_FLAGS {
   public static final int GIMBAL_MANAGER_FLAGS_RETRACT = 1; /* Based on GIMBAL_DEVICE_FLAGS_RETRACT | */
   public static final int GIMBAL_MANAGER_FLAGS_NEUTRAL = 2; /* Based on GIMBAL_DEVICE_FLAGS_NEUTRAL | */
   public static final int GIMBAL_MANAGER_FLAGS_ROLL_LOCK = 4; /* Based on GIMBAL_DEVICE_FLAGS_ROLL_LOCK | */
   public static final int GIMBAL_MANAGER_FLAGS_PITCH_LOCK = 8; /* Based on GIMBAL_DEVICE_FLAGS_PITCH_LOCK | */
   public static final int GIMBAL_MANAGER_FLAGS_YAW_LOCK = 16; /* Based on GIMBAL_DEVICE_FLAGS_YAW_LOCK | */
   public static final int GIMBAL_MANAGER_FLAGS_ENUM_END = 17; /*  | */
}
            