/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class HEADING_TYPE {
   public static final int HEADING_TYPE_COURSE_OVER_GROUND = 0; /*  | */
   public static final int HEADING_TYPE_HEADING = 1; /*  | */
   public static final int HEADING_TYPE_ENUM_END = 2; /*  | */
}
            