/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL {
   public static final int MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_LOW = 0; /* Switch Low. |Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)|  */
   public static final int MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_MIDDLE = 1; /* Switch Middle. |Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)|  */
   public static final int MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_HIGH = 2; /* Switch High. |Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)| Reserved (default:0)|  */
   public static final int MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_ENUM_END = 3; /*  | */
}
            