/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Enumeration of distance sensor types
*/
public class MAV_DISTANCE_SENSOR {
   public static final int MAV_DISTANCE_SENSOR_LASER = 0; /* Laser altimeter, e.g. LightWare SF02/F or PulsedLight units | */
   public static final int MAV_DISTANCE_SENSOR_ULTRASOUND = 1; /* Ultrasound altimeter, e.g. MaxBotix units | */
   public static final int MAV_DISTANCE_SENSOR_ENUM_END = 2; /*  | */
}
            