/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * The error type for the OSD parameter editor.
 */
public class OSD_PARAM_CONFIG_ERROR {
   public static final int OSD_PARAM_SUCCESS = 0; /*  | */
   public static final int OSD_PARAM_INVALID_SCREEN = 1; /*  | */
   public static final int OSD_PARAM_INVALID_PARAMETER_INDEX = 2; /*  | */
   public static final int OSD_PARAM_INVALID_PARAMETER = 3; /*  | */
   public static final int OSD_PARAM_CONFIG_ERROR_ENUM_END = 4; /*  | */
}
            