/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* RTK GPS baseline coordinate system, used for RTK corrections
*/
public class RTK_BASELINE_COORDINATE_SYSTEM {
   public static final int RTK_BASELINE_COORDINATE_SYSTEM_ECEF = 0; /* Earth-centered, Earth-fixed | */
   public static final int RTK_BASELINE_COORDINATE_SYSTEM_NED = 1; /* North, East, Down | */
   public static final int RTK_BASELINE_COORDINATE_SYSTEM_ENUM_END = 2; /*  | */
}
            