/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class SCRIPTING_CMD {
   public static final int SCRIPTING_CMD_REPL_START = 0; /* Start a REPL session. | */
   public static final int SCRIPTING_CMD_REPL_STOP = 1; /* End a REPL session. | */
   public static final int SCRIPTING_CMD_ENUM_END = 2; /*  | */
}
            