/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * 
 */
public class SPEED_TYPE {
   public static final int SPEED_TYPE_AIRSPEED = 0; /*  | */
   public static final int SPEED_TYPE_GROUNDSPEED = 1; /*  | */
   public static final int SPEED_TYPE_ENUM_END = 2; /*  | */
}
            