/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * State flags for ADS-B transponder fault report
 */
public class UAVIONIX_ADSB_OUT_STATUS_FAULT {
   public static final int UAVIONIX_ADSB_OUT_STATUS_FAULT_STATUS_MESSAGE_UNAVAIL = 8; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_FAULT_GPS_NO_POS = 16; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_FAULT_GPS_UNAVAIL = 32; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_FAULT_TX_SYSTEM_FAIL = 64; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_FAULT_MAINT_REQ = 128; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_FAULT_ENUM_END = 129; /*  | */
}
            