/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * State flags for ADS-B transponder status report
 */
public class UAVIONIX_ADSB_OUT_STATUS_STATE {
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_ON_GROUND = 1; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_INTERROGATED_SINCE_LAST = 2; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_XBIT_ENABLED = 4; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_IDENT_ACTIVE = 8; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_MODE_A_ENABLED = 16; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_MODE_C_ENABLED = 32; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_MODE_S_ENABLED = 64; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_1090ES_TX_ENABLED = 128; /*  | */
   public static final int UAVIONIX_ADSB_OUT_STATUS_STATE_ENUM_END = 129; /*  | */
}
            