/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * State flags for X-Bit and reserved fields.
 */
public class UAVIONIX_ADSB_XBIT {
   public static final int UAVIONIX_ADSB_XBIT_ENABLED = 128; /*  | */
   public static final int UAVIONIX_ADSB_XBIT_ENUM_END = 129; /*  | */
}
            